[package]
name = "transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.2.1", features = ["full", "signer-local"] }
tokio = { version = "1.49.0", features = ["full"] }
eyre = "0.6"
dotenv = "0.15"